### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [A-PS1999/seo-research-assistant-project#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by A-PS1999** [comment]
Thank you for creating this issue and pointing it out to me. I have just added the GNU General Public License 3.0 to the project.
